name: 'Check Lingua Franca files'
description: 'Ensure that all Lingua Franca files compile'
author: 'Marten Lohstroh'
inputs:
  checkout_dir:
    required: false
    description: 'Where the lingua-franca repo should be'
    default: 'lingua-franca'
  compiler_ref:
    required: false
    description: 'Which version of the compiler to use'
    default: 'master'
  delete_if_exists:
    required: false
    description: 'Delete if `checkout_dir` already exists'
    default: false
  exclude_dirs:
    required: false
    description: 'JSON array of directories not to visit'
    default: '["failing"]'
  no_compile_flag:
    required: false
    description: 'un lfc with `--no-compile` flag if true'
    default: false
  skip_clone:
    required: false
    description: 'Use existing clone of `lingua-franca`'
    default: false
  search_dir:
    required: false
    description: 'Where to start looking for `.lf` files'
    default: '.'
  
runs:
  using: 'node16'
  main: 'dist/index.js'
